### ISSUE TITLE
Option to hide icon when no inhibitors are active?

### ISSUE THREAD

**Issue by DarwinAwardWinner** [monyxie/inhibitionindicator#1]
In the interest of minimizing unnecessary clutter, it would be nice to have an option to only show the menu icon when sleep is currently inhibited and otherwise show nothing.

**Comment by monyxie** [comment]
Good idea. I'll see what I can do once I have time.

**Comment by monyxie** [comment]
It's on main now and will be included in the next release.

**Comment by monyxie** [comment]
Shipped in version 3.
